---
# handlers file for pre-deploy
- name: restart resolved                                
  tags:                                                                                                
  - service                                                                                                                          
  service:                                                                                        
    name: systemd-resolved                                                                                
    state: restarted                                                                                   
