---
# tasks file for os_identity-project

- name: Create project named {{ project_name }}
  os_project:
    cloud: "{{CLOUD_NAME}}"
    endpoint_type: admin
    state: present
    name: "{{ project_name }}"
    description: "{{ project_desc }}" 
    domain_id: "{{ domain_ID }}"
    enabled: True

# Delete a project
- name: Delete project named {{ project_name }}
  os_project:
    cloud: "{{CLOUD_NAME}}"
    endpoint_type: admin
    state: absent
    name: "{{ project_name }}"
  tags: [ never, del-project ]
